<a href="https://colab.research.google.com/github/jbogacz/data-science-bootcamp/blob/main/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.__version__

'1.24.2'

In [ ]:
x = np.array([1, 2, 3])
x.ndim
x.shape

(3,)

In [ ]:
x = np.array([[[1, 2, 3], [1, 1, 1], [1, 1, 1]], [[1, 1, 1] ,[1, 1, 1] ,[1, 1, 1]], [[1, 1, 1], [1, 1, 1], [1, 1, 1]]])
x

array([[[1, 2, 3],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.linspace(start=0 ,stop=1, num=11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
A.reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A.reshape(3, -1)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [ ]:
A + B

array([6, 0, 7, 4])

In [ ]:
A - B


array([0, 2, 1, 0])

In [ ]:
A * B

array([ 9, -1, 12,  4])

In [ ]:
np.multiply(A, B)

array([ 9, -1, 12,  4])

In [ ]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [ ]:
A + 2

array([5, 3, 6, 4])

In [ ]:
A + 3*B

array([12, -2, 13,  8])

Mnożenie macieżowe

In [ ]:
X = np.array([[1,3], [-2, 0]])
Y = np.array([[6,0], [-1, 2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [ ]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [ ]:
X @ Y

array([[  3,   6],
       [-12,   0]])

Generowanie liczb losowych

Ustawiamy ziarno zeby zawsze uzyskac te same 'pseudo' losowe liczby

In [ ]:
np.random.seed(0)

In [ ]:
np.random.randn(10)

array([-2.36958691,  0.8640523 , -2.23960406,  0.40149906,  1.22487056,
        0.06485611, -1.27968917, -0.5854312 , -0.26164545, -0.18224478])

In [ ]:
np.random.randn(10, 3)

array([[-0.20289684, -0.10988278,  0.21348005],
       [-1.20857365, -0.24201983,  1.51826117],
       [-0.38464542, -0.44383609,  1.0781973 ],
       [-2.55918467,  1.1813786 , -0.63190376],
       [ 0.16392857,  0.09632136,  0.94246812],
       [-0.26759475, -0.67802578,  1.29784579],
       [-2.36417382,  0.02033418, -1.34792542],
       [-0.76157339,  2.01125668, -0.04459543],
       [ 0.1950697 , -1.78156286, -0.72904466],
       [ 0.1965574 ,  0.35475769,  0.61688655]])

In [ ]:
np.random.randint(low=10, high=101)


85

In [ ]:
np.random.choice([1,2,6,12,6])

6

In [ ]:
data = np.arange(10)
np.random.shuffle(data)
data

array([6, 4, 1, 5, 2, 0, 8, 3, 7, 9])

Indeksowanie i wycinanie

In [ ]:
A = np.arange(20)
A[0:3], A

(array([0, 1, 2]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19]))

In [ ]:
A[-1]

19

In [ ]:
A = A.reshape(4, 5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
A[0]

array([0, 1, 2, 3, 4])

In [ ]:
A[:, 0]

array([ 0,  5, 10, 15])

In [ ]:
A[:, -1]

array([ 4,  9, 14, 19])

In [ ]:
A[1, 1]

6

In [ ]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [ ]:
A[1 , 2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iteracja po tablicach

In [ ]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

Iterowanie po elementach tablicy

In [ ]:
for row in A:
  print(row)

[0 1 2]
[ 5  6 14]
[10 11 12]
[15 16 17]


In [ ]:
for row in A:
  print(row[0])

In [ ]:
for row in A:
  print(row[:3])

In [ ]:
for item in A.flat:
  print(item)

Zmiana rozmiaru tablicy

In [ ]:
A.shape

(4, 5)

In [ ]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
## flatten array
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
## transpose
B = np.arange(6).reshape(2,3)
B, B.T

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[0, 3],
        [1, 4],
        [2, 5]]))

Maski logiczne

In [ ]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [ ]:
# prepare mask where elements greater than 0
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [ ]:
# take elements base on a mask
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [ ]:
# mask with AND condition
M = np.bitwise_and(A > -5, A < 5)
A[M]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])